### ISSUE TITLE
Improve forms with React forms

### ISSUE THREAD

**Issue by yacinec** [yacinec/BuyIt#15]
Improve current forms with React Forms: https://react-hook-form.com/

**Comment by akinsanmi60** [comment]
Hi, how is the backend started... After installing the dependencies, i was unable to start it. I start with npm start. Kindly reply me

**Comment by yacinec** [comment]
Hello @akinsanmi60, thanks for your interest for the project! You need to create an .env file in the back folder with these informations:

- PORT
- DATABASE_URI
- ACCESS_TOKEN_PRIVATE_KEY
- ACCESS_TOKEN_PUBLIC_KEY
- REFRESH_TOKEN_PRIVATE_KEY

You also need to have a [mongodb](https://www.mongodb.com/) database to use the app.
After that, you will be able to run the backend:

`npm run dev`

and then the frontend:

`npm start`

However, I'm already working on this issue (Improve forms with React forms #15) 😉

**Comment by akinsanmi60** [comment]
Okay
